"""
Scrambler utility implementing a simple LFSR-based pseudo-random sequence generator.

This is a placeholder for the SDA OCT-compliant scrambler. It provides:
- deterministic bit stream generator given a seed and polynomial
- XOR scrambling/descrambling for bytes payloads
"""

from dataclasses import dataclass


@dataclass
class LFSR:
    """Simple LFSR for pseudo-random bit generation."""

    seed: int = 0xACE1
    poly_taps: int = 0b1000000000000101  # x^16 + x^2 + x^0 (example)
    width: int = 16

    def step(self) -> int:
        """Advance LFSR one step and return output bit."""
        # XOR of tapped bits
        taps = self.poly_taps & ((1 << self.width) - 1)
        feedback = 0
        val = self.seed
        for i in range(self.width):
            if taps & (1 << i):
                feedback ^= (val >> i) & 1
        out = val & 1
        self.seed = ((val >> 1) | (feedback << (self.width - 1))) & ((1 << self.width) - 1)
        return out

    def byte(self) -> int:
        """Return a byte generated by 8 steps."""
        v = 0
        for i in range(8):
            v |= (self.step() & 1) << i
        return v & 0xFF


# PUBLIC_INTERFACE
def scramble(data: bytes, seed: int = 0xACE1) -> bytes:
    """Scramble data with XOR mask from LFSR."""
    l = LFSR(seed=seed)
    return bytes((b ^ l.byte()) & 0xFF for b in data)


# PUBLIC_INTERFACE
def descramble(data: bytes, seed: int = 0xACE1) -> bytes:
    """Descramble data (XOR with same mask regenerates original)."""
    return scramble(data, seed=seed)
